//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=E:\\Inżynieria\\Ćwiczenia\\GH\\GitHubQui" +
            "z\\Quiz\\Quiz\\bazaDanychQuiz.mdf;Integrated Security=True;Connect Timeout=30")]
        public string bazaDanychQuizConnectionString {
            get {
                return ((string)(this["bazaDanychQuizConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\Bartek\\Downloads\\Nowy fold" +
            "er\\Quiz\\Quiz\\bazaDanychQuiz.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string bazaDanychQuizConnectionString1 {
            get {
                return ((string)(this["bazaDanychQuizConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=E:\\Inżynieria\\Ćwiczenia\\GH\\GitHubQui" +
            "z\\Quiz\\bazaDanychQuiz.mdf;Integrated Security=True;Connect Timeout=30")]
        public string bazaDanychQuizConnectionString2 {
            get {
                return ((string)(this["bazaDanychQuizConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Bartek\\Downloads\\nowyfolder" +
            "2\\quizek\\Quiz\\bazaDanychQuiz.mdf;Integrated Security=True;Connect Timeout=30")]
        public string bazaDanychQuizConnectionString3 {
            get {
                return ((string)(this["bazaDanychQuizConnectionString3"]));
            }
        }
    }
}
